version: '3.9'
services:
    wsgi:
        build: ./
        container_name: flask_wsgi
        restart: always
        environment: 
                - FLASK_APP=app
                - FLASK_DEBUG=1
        links:
                - db
                - cache
        ports:
                - 5000:5000
        volumes:
                - './web/project:/app'
 #       command: gunicorn -w 1 -b 0.0.0.0:5000 app:app flask run

        command: flask run --host=0.0.0.0 --port=5000

    nginx:
        image: nginx
        container_name: flask_nginx
        restart: always
        ports:
                - 80:80
        volumes:
                - './web:/usr/share/nginx/html'
    
    db:
        image: mysql:5.7
        restart: always
        container_name: flask_db
        ports:
                - "3307:3306"
        expose:
                - "3307"
        environment:
                - MYSQL_USER=user
                - MYSQL_PASSWORD=user123
                - MYSQL_DATABASE=flask_api
                - MYSQL_ROOT_PASSWORD=12345678
        volumes:
                - ./db:/docker-entrypoint-initdb.d/:ro

    cache:
        image: redis
        restart: always
        container_name: flask_cache