apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.container.name }}
  namespace: {{ .Values.namespace }}
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.app }}
      environment: {{ .Values.environment }}
  template:
    metadata:
      labels:
        app: {{ .Values.app }}
        environment: {{ .Values.environment }}
    spec:
      containers:
        - name: {{ .Values.container.name }}
          image: {{ .Values.container.image }}:{{ .Values.container.tag }}
          imagePullPolicy: {{ .Values.container.imagePullPolicy }}
          ports:
            - containerPort: {{ .Values.container.port }}
          volumeMounts:
            - name: {{ .Values.pvc.volume }}
              mountPath: {{ .Values.pvc.path }}
          resources:
            requests:
              cpu: "100m"
              memory: "512Mi"
            limits:
              cpu: "500m"
              memory: "1024Mi"
          env:
            - name: environment
              value: {{ .Values.environment }}
            - name: MYSQL_DATABASE
              value: {{ .Values.db.name }}
            - name: MYSQL_ROOT_PASSWORD
              value: {{ .Values.db.rootpassword }}
            - name: MYSQL_USER
              value: {{ .Values.db.user }}
            - name: MYSQL_PASSWORD
              value: {{ .Values.db.userpassword }}
      volumes:
        - name: {{ .Values.pvc.volume }}
          persistentVolumeClaim:
            claimName: {{ .Values.pvc.claim }}
