apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.container.name }}-service
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Values.app }}
    environment: {{ .Values.environment }}
spec:
  ports:
  - port: {{ .Values.container.port }}
    protocol: TCP
    targetPort: {{ .Values.container.port }}
  selector:
    app: {{ .Values.app }}
    environment: {{ .Values.environment }}
  type: NodePort
