kind: ConfigMap
apiVersion: v1
metadata:
  name: nginx-config
data:
  default.conf: |
      http {
        upstream app {
            server mgl7760-h2023-projet1-groupe-3-wsgi-1:5000;
            server mgl7760-h2023-projet1-groupe-3-wsgi-2:5000;
            server mgl7760-h2023-projet1-groupe-3-wsgi-3:5000;
                }
        server {
            listen 80;
            listen  [::]:80;
            server_name localhost;
            location / {
                proxy_pass http://app;
                    }
                }
            }
