apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.container.name }}
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.container.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.container.name }}
        environment: {{ .Values.environment }}
    spec:
      containers:
        - name: {{ .Values.container.name }}
          image: {{ .Values.container.image }}:{{ .Values.container.tag }}
          ports:
            - containerPort: {{ .Values.container.port }}
          env:
            - name: environment
              value: {{ .Values.environment }}
          volumeMounts:
            - name: {{ .Values.cm.name }}
              mountPath: {{ .Values.cm.path }}
            - name: {{ .Values.pvc.name }}
              mountPath: {{ .Values.pvc.path }}
      volumes:
        - name: {{ .Values.cm.name }}
          configMap:
            name: nginx-config
        - name: {{ .Values.pvc.name }}
          persistentVolumeClaim:
            claimName: {{ .Values.pvc.claim }}
